_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 77
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 3
                - 8
            "12": 0.19.1
            "13": windows-amd64
chemical:
    value:
        fingerprint_size: 1024
        radius: 2
        representation: FINGERPRINT
        sanitize: true
        use_chirality: true
        use_features: true
data:
    value:
        cache_data: true
        chunk_size: 10000
        curves_post_qc: ${DATA_DIR:-data}/raw/CTRP/v20.data.curves_post_qc.txt
        feature_space: LANDMARK
        gctx_file: $./data/processed/LINCS.gctx
        geneinfo_file: ${DATA_DIR:-data}/raw/LINCS/geneinfo_beta.txt
        matching_strategy: parallel
        max_workers: null
        normalize: ZSCORE
        nrows: 1000
        num_workers: 4
        output_path: ${DATA_DIR:-data}/processed/LINCS_CTRP_matched.gctx
        per_cell_line: ${DATA_DIR:-data}/raw/CTRP/v20.meta.per_cell_line.txt
        per_compound: ${DATA_DIR:-data}/raw/CTRP/v20.meta.per_compound.txt
        per_cpd_post_qc: ${DATA_DIR:-data}/raw/CTRP/v20.data.per_cpd_post_qc.txt
        per_experiment: ${DATA_DIR:-data}/raw/CTRP/v20.meta.per_experiment.txt
        random_seed: 42
        siginfo_file: ${DATA_DIR:-data}/raw/LINCS/siginfo_beta.txt
        use_multiprocessing: true
deployment:
    value:
        quantization:
            - static
            - dynamic
evaluation:
    value:
        loss: mse
        metrics:
            - r2
            - rmse
            - mae
            - pearson
        output_dir: results/eval
        visualization:
            dpi: 300
            figsize:
                - 10
                - 8
experiment:
    value:
        checkpoint_freq: 5
        keep_n_checkpoints: 3
        project_name: lincs_ctrp_prediction
        run_name: ${RUN_NAME:-run_20250304_151607}
        save_checkpoints: true
        tags:
            - multimodal
            - drug-response
        track: false
        version: 1.0.0
inference:
    value:
        device: cuda
        export_formats:
            - pytorch
            - onnx
            - torchscript
        max_ensemble: 5
        output_path: results/predictions.csv
model:
    value:
        activation: RELU
        chemical_hidden_dims:
            - 256
            - 128
        chemical_input_dim: 1025
        chemical_output_dim: 128
        dropout: 0.3
        fusion_output_dim: 256
        fusion_strategy: CONCAT
        layer_norm: true
        normalize: true
        predictor_hidden_dims:
            - 128
            - 64
        residual_connections: true
        transcriptomics_hidden_dims:
            - 512
            - 256
        transcriptomics_input_dim: 978
        transcriptomics_output_dim: 128
        use_batch_norm: true
paths:
    value:
        data_dir: $data
        log_dir: $logs
        model_dir: $models/saved
        results_dir: $results
training:
    value:
        batch_size: 32
        clip_grad_norm: true
        early_stopping: true
        epochs: 100
        group_by: null
        label_smoothing: 0.1
        learning_rate: 0.001
        loss: MSE
        lr_scheduler:
            min_lr: 1e-06
            type: step
            warmup_epochs: 5
        max_grad_norm: 1
        min_delta: 0.001
        optimizer: ADAM
        patience: 10
        random_state: 42
        stratify_by: null
        test_size: 0.2
        use_amp: true
        val_size: 0.1
        weight_decay: 0.01
