# config.yaml
# Environment variables
# These will be resolved at runtime using the resolve_path_variables function
# Use format: ${ENV_VAR_NAME} or ${ENV_VAR_NAME:-default_value}
paths:
  data_dir: "${DATA_DIR:-data}"
  model_dir: "${MODEL_DIR:-models/saved}"
  log_dir: "${LOG_DIR:-logs}"
  results_dir: "${RESULTS_DIR:-results}"

data:
  # LINCS files
  gctx_file: "${DATA_DIR:-data}/raw/LINCS/level5_beta_trt_cp_n720216x12328.gctx"
  geneinfo_file: "${DATA_DIR:-data}/raw/LINCS/geneinfo_beta.txt"
  siginfo_file: "${DATA_DIR:-data}/raw/LINCS/siginfo_beta.txt"

  # CTRP files
  curves_post_qc: "${DATA_DIR:-data}/raw/CTRP/v20.data.curves_post_qc.txt"
  per_cpd_post_qc: "${DATA_DIR:-data}/raw/CTRP/v20.data.per_cpd_post_qc.txt"
  per_experiment: "${DATA_DIR:-data}/raw/CTRP/v20.meta.per_experiment.txt"
  per_compound: "${DATA_DIR:-data}/raw/CTRP/v20.meta.per_compound.txt"
  per_cell_line: "${DATA_DIR:-data}/raw/CTRP/v20.meta.per_cell_line.txt"

  # Output configuration
  output_path: "${DATA_DIR:-data}/processed/LINCS_CTRP_matched.gctx"

  # Processing options
  feature_space: "landmark"
  nrows: 2000
  normalize: "zscore"
  random_seed: 42
  cache_data: true
  use_multiprocessing: true
  num_workers: 4

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  optimizer: "adamw"
  loss: "mse"
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  group_by: null # Set to a column name for group-based splitting
  stratify_by: null # Set to a column name for stratified splitting

  # Learning rate scheduling
  lr_scheduler:
    type: "cosine"
    warmup_epochs: 5
    min_lr: 0.000001

  # Early stopping
  early_stopping: true
  patience: 10
  min_delta: 0.001

  # Training options
  clip_grad_norm: true
  max_grad_norm: 1.0
  use_amp: true
  weight_decay: 0.01
  label_smoothing: 0.1

chemical:
  representation: "fingerprint"
  fingerprint_size: 1024
  radius: 2
  use_chirality: true
  use_features: true
  sanitize: true

model:
  transcriptomics_input_dim: 978
  transcriptomics_hidden_dims: [512, 256]
  transcriptomics_output_dim: 128
  chemical_input_dim: 1025
  chemical_hidden_dims: [256, 128]
  chemical_output_dim: 128
  fusion_output_dim: 256
  fusion_strategy: "concat"
  predictor_hidden_dims: [64, 32]
  normalize: true
  dropout: 0.3
  activation: "relu"
  use_batch_norm: true
  layer_norm: true
  residual_connections: true

experiment:
  project_name: "lincs_ctrp_prediction"
  run_name: null # Will be auto-generated if null
  track: true # Set to true to enable experiment tracking
  tags: ["multimodal", "drug-response"]
  version: "1.0.0"
  save_checkpoints: true
  checkpoint_freq: 5
  keep_n_checkpoints: 3
