# config.yaml
paths:
  data_dir: "data"
  model_dir: "models/saved"
  log_dir: "logs"
  results_dir: "results"
  checkpoint_dir: "models/saved/checkpoints"

data:
  gctx_file: "data/processed/LINCS.gctx"
  geneinfo_file: "data/raw/LINCS/geneinfo_beta.txt"
  siginfo_file: "data/raw/LINCS/siginfo_beta.txt"
  curves_post_qc: "data/raw/CTRP/v20.data.curves_post_qc.txt"
  per_cpd_post_qc: "data/raw/CTRP/v20.data.per_cpd_post_qc.txt"
  per_experiment: "data/raw/CTRP/v20.meta.per_experiment.txt"
  per_compound: "data/raw/CTRP/v20.meta.per_compound.txt"
  per_cell_line: "data/raw/CTRP/v20.meta.per_cell_line.txt"
  output_path: "data/processed/LINCS_CTRP_matched.gctx"
  matching_strategy: "parallel"
  max_workers: null
  chunk_size: 10000
  feature_space: "landmark"
  nrows: 1000
  normalize: "zscore"
  random_seed: 42
  cache_data: true
  use_multiprocessing: true
  num_workers: 0
  batch_size: 32
  imputation_strategy: "mean"
  handle_outliers: false
  outlier_threshold: 3.0

training:
  batch_size: 32
  epochs: 100
  num_runs: 5
  learning_rate: 0.001
  optimizer: "adam" # Adjusted to match trainer.py (add "adamw" support if needed)
  loss: "mse"
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  group_by: null
  stratify_by: null
  lr_scheduler:
    type: "step" # Adjusted to match trainer.py (add "cosine" support if needed)
    step_size: 10
    gamma: 0.1
  early_stopping: true
  patience: 10
  min_delta: 0.001
  clip_grad_norm: true
  max_grad_norm: 1.0
  use_amp: true
  weight_decay: 0.01
  label_smoothing: 0.1

molecular:
  representation: "fingerprint"
  fingerprint_size: 1024
  radius: 2
  use_chirality: true
  use_features: true
  sanitize: true

model:
  transcriptomics_input_dim: 978
  transcriptomics_hidden_dims: [512, 256]
  transcriptomics_output_dim: 128
  molecular_input_dim: 1025 # Changed from chemical_input_dim
  molecular_hidden_dims: [256, 128] # Changed from chemical_hidden_dims
  molecular_output_dim: 128 # Changed from chemical_output_dim
  fusion_output_dim: 256
  predictor_hidden_dims: [128, 64]
  transcriptomics_encoder_type: "mlp"
  molecular_encoder_type: "descriptors" # Changed from chemical_encoder_type
  fusion_type: "simple"
  fusion_strategy: "concat"
  activation: "relu"
  dropout: 0.3
  normalize: true
  use_batch_norm: true
  predictor_type: "standard"

evaluation:
  metrics: ["r2", "rmse", "mae", "pearson"]
  loss: "mse"
  output_dir: "results/eval"
  visualization:
    dpi: 300
    figsize: [10, 8]

inference:
  device: "cuda"
  max_ensemble: 5
  output_path: "results/predictions.csv"
  export_formats: ["pytorch", "onnx", "torchscript"]

deployment:
  quantization: ["static", "dynamic"]

experiment:
  project_name: "lincs_ctrp_prediction"
  run_name: "${RUN_NAME:-run_${timestamp}}"
  track: false
  tags: ["multimodal", "drug-response"]
  version: "1.0.0"
  save_checkpoints: true
  checkpoint_freq: 5
  keep_n_checkpoints: 3
  log_level: "WARNING"

interpretation:
  enabled: true
  attribution_methods:
    - "integrated_gradients"
    - "feature_ablation"
    - "deep_lift"
  n_samples: 5 # Number of samples to use for interpretation
  top_k: 20 # Number of top features to highlight
  visualize_features: true
  feature_naming:
    transcriptomics: "data/raw/LINCS/geneinfo_beta.txt" # Path to gene name mapping
    molecular: null # No naming for molecular features
  save_attributions: true # Whether to save raw attribution values
  generate_figures: true
