# config.yaml
paths:
  data_dir: "data"
  model_dir: "models/saved"
  log_dir: "logs"
  results_dir: "results"
  checkpoint_dir: "models/saved/checkpoints"

data:
  lincs_file: "data/processed/LINCS_small_updated.gctx"
  mixseq_file: "data/processed/MixSeq.gctx"
  geneinfo_file: "data/raw/LINCS/geneinfo_beta.txt"
  siginfo_file: "data/raw/LINCS/siginfo_beta.txt"
  curves_post_qc: "data/raw/CTRP/v20.data.curves_post_qc.txt"
  per_cpd_post_qc: "data/raw/CTRP/v20.data.per_cpd_post_qc.txt"
  per_experiment: "data/raw/CTRP/v20.meta.per_experiment.txt"
  per_compound: "data/raw/CTRP/v20.meta.per_compound.txt"
  per_cell_line: "data/raw/CTRP/v20.meta.per_cell_line.txt"
  output_path: "data/processed/LINCS_CTRP_matched.gctx"
  matching_strategy: "parallel"
  max_workers: null
  chunk_size: 10000
  feature_space: "landmark"
  nrows: 1000
  normalize: "none"
  random_seed: 42
  cache_data: true
  use_multiprocessing: true
  num_workers: 4
  imputation_strategy: "mean"
  handle_outliers: false
  outlier_threshold: 3.0

training:
  batch_size: 256
  epochs: 50
  num_runs: 3
  learning_rate: 0.001
  optimizer: "adam" 
  loss: "mse"
  test_size: 0.4
  val_size: 0.1
  random_state: 42
  group_by: "cell_mfc_name"
  stratify_by: "viability_clipped"
  lr_scheduler:
    type: "step" 
    warmup_epochs: 5
    min_lr: 1e-6
    step_size: 10
    gamma: 0.1
  early_stopping: true
  patience: 10
  min_delta: 0.001
  clip_grad_norm: true
  max_grad_norm: 1.0
  use_amp: true
  weight_decay: 0.01
  label_smoothing: 0.1

molecular:
  representation: "fingerprint"
  fingerprint_size: 1024
  radius: 2
  use_chirality: true
  use_features: true
  sanitize: true

model:
  transcriptomics_input_dim: 978
  transcriptomics_hidden_dims: [512, 256]
  transcriptomics_output_dim: 128
  molecular_input_dim: 1025 
  molecular_hidden_dims: [256, 128] 
  molecular_output_dim: 128 
  fusion_output_dim: 256
  predictor_hidden_dims: [128, 64]
  transcriptomics_encoder_type: "mlp"
  molecular_encoder_type: "descriptors"
  fusion_type: "simple"
  fusion_strategy: "concat"
  activation: "relu"
  dropout: 0.3
  normalize: true
  use_batch_norm: true
  predictor_type: "standard"

evaluation:
  metrics: ["r2", "rmse", "mae", "pearson"]
  loss: "mse"
  output_dir: "results/eval"
  visualization:
    dpi: 300
    figsize: [10, 8]

inference:
  device: "cuda"
  max_ensemble: 5
  output_path: "results/predictions.csv"
  export_formats: ["pytorch", "onnx", "torchscript"]

deployment:
  quantization: ["static", "dynamic"]

experiment:
  project_name: "lincs_ctrp_prediction"
  run_name: "${RUN_NAME:-run_${timestamp}}"
  track: true
  tags: ["multimodal", "drug-response"]
  version: "1.0.0"
  save_checkpoints: true
  checkpoint_freq: 5
  keep_n_checkpoints: 3
  log_level: "WARNING"

interpretation:
  enabled: true
  attribution_methods:
    - "integrated_gradients"
    - "feature_ablation"
    - "deep_lift"
  n_samples: 5 
  top_k: 20 
  visualize_features: true
  feature_naming:
    transcriptomics: "data/raw/LINCS/geneinfo_beta.txt" # Path to gene name mapping
    molecular: null 
  save_attributions: true 
  generate_figures: true
