data_paths:
  compoundinfo_file: "data/raw/compoundinfo.csv"
  x_file: "data/raw/X.tsv"
  y_file: "data/raw/Y.tsv"
  rna_file: "data/raw/X_RNA.bin"
  geneinfo_file: "data/raw/geneinfo_beta.txt"
  preprocessed_tf_file: "data/processed/preprocessed_tf.csv"
  preprocessed_gene_file: "data/processed/preprocessed_gene.csv"
  output_file: "data/processed/final_dataset.csv"

preprocess_params:
  scale_features: true
