stages:
  preprocess:
    cmd: python src/preprocess/preprocess.py --config_file config.yaml
    deps:
      - src/preprocess/preprocess.py
      - config.yaml
      - data/raw

    outs:
      - data/processed/final_dataset.csv
