stages:
  preprocess:
    cmd: python src/preprocess/preprocess.py --config_file config.yaml
    deps:
      - src/preprocess/preprocess.py
      - config.yaml
      - data/raw/compoundinfo.csv
      - data/raw/X.tsv
      - data/raw/Y.tsv
    outs:
      - data/processed/final_dataset.csv
