# src/config/default_config.py
from typing import Any, Dict


def get_default_config() -> Dict[str, Any]:
    """Get default configuration settings."""
    config = {
        "paths": {
            "data_dir": "${DATA_DIR:-data}",
            "model_dir": "${MODEL_DIR:-models/saved}",
            "log_dir": "${LOG_DIR:-logs}",
            "results_dir": "${RESULTS_DIR:-results}",
            "checkpoint_dir": "${CHECKPOINT_DIR:-models/saved/checkpoints}",
        },
        "data": {
            "gctx_file": "${DATA_DIR:-data}/raw/LINCS/level5_beta_trt_cp_n720216x12328.gctx",
            "geneinfo_file": "${DATA_DIR:-data}/raw/LINCS/geneinfo_beta.txt",
            "siginfo_file": "${DATA_DIR:-data}/raw/LINCS/siginfo_beta.txt",
            "curves_post_qc": "${DATA_DIR:-data}/raw/CTRP/v20.data.curves_post_qc.txt",
            "per_cpd_post_qc": "${DATA_DIR:-data}/raw/CTRP/v20.data.per_cpd_post_qc.txt",
            "per_experiment": "${DATA_DIR:-data}/raw/CTRP/v20.meta.per_experiment.txt",
            "per_compound": "${DATA_DIR:-data}/raw/CTRP/v20.meta.per_compound.txt",
            "per_cell_line": "${DATA_DIR:-data}/raw/CTRP/v20.meta.per_cell_line.txt",
            "output_path": "${DATA_DIR:-data}/processed/LINCS_CTRP_matched.gctx",
            "matching_strategy": "parallel",
            "max_workers": None,
            "chunk_size": 10000,
            "feature_space": "landmark",
            "nrows": 100,
            "normalize": "zscore",
            "random_seed": 42,
            "cache_data": True,
            "use_multiprocessing": True,
            "num_workers": 0,
            "batch_size": 32,
            "imputation_strategy": "mean",
            "handle_outliers": False,
            "outlier_threshold": 3.0,
        },
        "training": {
            "batch_size": 32,
            "epochs": 100,
            "num_runs": 5,
            "learning_rate": 0.001,
            "optimizer": "adamw",
            "loss": "mse",
            "test_size": 0.2,
            "val_size": 0.1,
            "random_state": 42,
            "group_by": None,
            "stratify_by": None,
            "lr_scheduler": {
                "type": "cosine",
                "warmup_epochs": 5,
                "min_lr": 1e-6,
                "step_size": 10,
                "gamma": 0.1,
            },
            "early_stopping": True,
            "patience": 10,
            "min_delta": 0.001,
            "clip_grad_norm": True,
            "max_grad_norm": 1.0,
            "use_amp": True,
            "weight_decay": 0.01,
            "label_smoothing": 0.1,
        },
        "molecular": {
            "representation": "fingerprint",
            "fingerprint_size": 1024,
            "radius": 2,
            "use_chirality": True,
            "use_features": True,
            "sanitize": True,
        },
        "model": {
            "transcriptomics_input_dim": 978,
            "transcriptomics_hidden_dims": [512, 256],
            "transcriptomics_output_dim": 128,
            "molecular_input_dim": 1025,
            "molecular_hidden_dims": [256, 128],
            "molecular_output_dim": 128,
            "fusion_output_dim": 256,
            "fusion_strategy": "concat",
            "predictor_hidden_dims": [128, 64],
            "normalize": True,
            "dropout": 0.3,
            "activation": "gelu",
            "use_batch_norm": True,
            "layer_norm": True,
            "residual_connections": True,
        },
        "experiment": {
            "project_name": "lincs_ctrp_prediction",
            "run_name": None,
            "track": True,
            "tags": ["multimodal", "drug-response"],
            "version": "1.0.0",
            "save_checkpoints": True,
            "checkpoint_freq": 5,
            "keep_n_checkpoints": 3,
            "log_level": "WARNING",
        },
        "evaluation": {
            "metrics": ["r2", "rmse", "mae", "pearson"],
            "loss": "mse",
            "output_dir": "results/eval",
            "visualization": {
                "dpi": 300,
                "figsize": [10, 8],
            },
        },
        "inference": {
            "device": "cuda",
            "max_ensemble": 5,
            "output_path": "results/predictions.csv",
            "export_formats": ["pytorch", "onnx", "torchscript"],
        },
        "deployment": {
            "quantization": ["static", "dynamic"],
        },
        "interpretation": {
            "enabled": True,
            "attribution_methods": [
                "integrated_gradients",
                "feature_ablation",
                "deep_lift",
            ],
            "n_samples": 5,
            "top_k": 20,
            "visualize_features": True,
            "feature_naming": {
                "transcriptomics": "data/raw/LINCS/geneinfo_beta.txt",
                "molecular": None,
            },
            "save_attributions": True,
            "generate_figures": True,
        },
    }
    return config
