_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
chemical:
    value:
        fingerprint_size: 1024
        radius: 2
        representation: fingerprint
data:
    value:
        feature_space: landmark
        gctx_file: ../data/processed/LINCS2.gctx
        nrows: 100
experiment:
    value:
        project_name: lincs_ctrp_debug
        run_name: 852704b8
        track: true
model:
    value:
        dropout: 0.3
        hidden_dims:
            - 64
            - 32
        input_dim: null
        type: SimpleNN
training:
    value:
        batch_size: 64
        epochs: 20
        group_by: null
        learning_rate: 0.001
        loss: mse
        optimizer: adam
        random_state: 42
        test_size: 0.2
        val_size: 0.1
