_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 21
                - 41
                - 49
                - 53
                - 55
                - 77
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 21
                - 41
                - 49
                - 53
                - 55
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "6": 4.47.0
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
architecture:
    value: Perturbinator
batch_size:
    value: 512
dataset:
    value: LINCS/CTRPv2
epochs:
    value: 20
lr:
    value: 0.001
