_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 77
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
                - 77
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 8
            "12": 0.19.1
            "13": linux-x86_64
data:
    value:
        cache_data: true
        chunk_size: 1000
        curves_post_qc: data/raw/CTRP/v20.data.curves_post_qc.txt
        feature_space: LANDMARK
        gctx_file: data/processed/LINCS.gctx
        geneinfo_file: data/raw/LINCS/geneinfo_beta.txt
        handle_outliers: false
        imputation_strategy: MEAN
        matching_strategy: parallel
        max_workers: null
        normalize: NONE
        nrows: 1000
        num_workers: 0
        outlier_threshold: 3
        output_path: data/processed/LINCS_CTRP_matched.gctx
        per_cell_line: data/raw/CTRP/v20.meta.per_cell_line.txt
        per_compound: data/raw/CTRP/v20.meta.per_compound.txt
        per_cpd_post_qc: data/raw/CTRP/v20.data.per_cpd_post_qc.txt
        per_experiment: data/raw/CTRP/v20.meta.per_experiment.txt
        random_seed: 42
        siginfo_file: data/raw/LINCS/siginfo_beta.txt
        use_multiprocessing: true
deployment:
    value:
        quantization:
            - static
            - dynamic
evaluation:
    value:
        loss: mse
        metrics:
            - r2
            - rmse
            - mae
            - pearson
        output_dir: results/eval
        visualization:
            dpi: 300
            figsize:
                - 10
                - 8
experiment:
    value:
        checkpoint_freq: 5
        keep_n_checkpoints: 3
        log_level: WARNING
        project_name: lincs_ctrp_prediction
        run_name: ${RUN_NAME:-run_20250306_140429}
        save_checkpoints: true
        tags:
            - multimodal
            - drug-response
        track: true
        version: 1.0.0
inference:
    value:
        device: cuda
        export_formats:
            - pytorch
            - onnx
            - torchscript
        max_ensemble: 5
        output_path: results/predictions.csv
interpretation:
    value:
        attribution_methods:
            - integrated_gradients
            - feature_ablation
            - deep_lift
        enabled: true
        feature_naming:
            molecular: null
            transcriptomics: data/raw/LINCS/geneinfo_beta.txt
        generate_figures: true
        n_samples: 5
        save_attributions: true
        top_k: 20
        visualize_features: true
model:
    value:
        activation: RELU
        dropout: 0.3
        fusion_output_dim: 256
        fusion_strategy: CONCAT
        layer_norm: true
        molecular_hidden_dims:
            - 256
            - 128
        molecular_input_dim: 1025
        molecular_output_dim: 128
        predictor_hidden_dims:
            - 128
            - 64
        residual_connections: true
        transcriptomics_hidden_dims:
            - 512
            - 256
        transcriptomics_input_dim: 978
        transcriptomics_output_dim: 128
        use_batch_norm: true
molecular:
    value:
        fingerprint_size: 1024
        radius: 2
        representation: FINGERPRINT
        sanitize: true
        use_chirality: true
        use_features: true
paths:
    value:
        checkpoint_dir: models/saved/checkpoints
        data_dir: data
        log_dir: logs
        model_dir: models/saved
        results_dir: results
training:
    value:
        batch_size: 128
        clip_grad_norm: true
        early_stopping: true
        epochs: 10
        group_by: cell_mfc_name
        label_smoothing: 0.1
        learning_rate: 0.001
        loss: MSE
        lr_scheduler:
            gamma: 0.1
            min_lr: 1e-06
            step_size: 10
            type: STEP
            warmup_epochs: 5
        max_grad_norm: 1
        min_delta: 0.001
        num_runs: 5
        optimizer: ADAM
        patience: 10
        random_state: 42
        stratify_by: viability
        test_size: 0.4
        use_amp: true
        val_size: 0.1
        weight_decay: 0.01
