_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 21
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 21
                - 49
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
